name: Build and Test

on:
  push:
    branches: [ "main" ]   # push 到 main 分支就觸發
  pull_request:
    branches: [ "main" ]   # PR 時也觸發

jobs:
    test:
        runs-on: ubuntu-latest   # 使用 GitHub 提供的 Ubuntu runner
        strategy:
            matrix:
                testproj:
                    - WebApp.Test/WebApp.Test.csproj
                    # Add more test projects here when needed
            fail-fast: false    # 讓其他測試持續執行，即使有一個失敗

        steps:
            - name: Checkout code
              uses: actions/checkout@v4   # 把程式碼抓下來

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: '9.0.x'   # 安裝 .NET 9

            - name: Restore dependencies
              run: dotnet restore

            - name: Build and Test
              run: |
                dotnet build --configuration Release --no-restore
                dotnet test ${{ matrix.testproj }} --configuration Release --verbosity normal